site_name: Tech Talk Live
site_url: https://ttl.iu13.net/
nav:
  - index.md
  - 'EVPN-VXLAN in the Collapsed Core':
    - '2026/evpn-vxlan/index.md'
  - TTL2024:
    - '2024/index.md'
    - 'Making NPS Logs Useful with Graylog':
      - '2024/graylog/index.md'
      - '2024/graylog/100-prerequisites.md'
      - '2024/graylog/200-nps.md'
      - '2024/graylog/220-ingest.md'
      - '2024/graylog/230-process.md'
      - '2024/graylog/240-aggregate.md'
      - '2024/graylog/300-conclusion.md'
    - 'Internet Exchange Peering':
      - '2024/peering/index.md'
  - TTL2023:
    - '2023/index.md'
    - 'Introduction to IPv6':
      - '2023/ipv6/index.md'
      - '2023/ipv6/100-design.md'
      - '2023/ipv6/200-routing.md'
      - '2023/ipv6/300-host-configuration.md'
      - '2023/ipv6/400-implementing.md'
      - '2023/ipv6/500-configuring.md'
      - '2023/ipv6/lab.md'
    - 'Routing Security — BGP, IRR, and RPKI':
      - '2023/routing-security/index.md'
      - '2023/routing-security/100-irr.md'
      - '2023/routing-security/200-rpki.md'
  - about.md
theme:
  name: material
  features:
#    - navigation.instant
    - navigation.tabs
#    - navigation.sections
    - toc.integrate
    - navigation.footer
    - navigation.tracking
    - navigation.prune
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    annotation: material/information
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/dsbaker1/
copyright: "Copyright © Dan Baker"
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - tables
  - pymdownx.details

plugins:
  - glightbox
